# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resys.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resys.proto',
  package='resys',
  syntax='proto3',
  serialized_options=_b('\n\007io.grpcB\nResysProtoP\001\242\002\002RS'),
  serialized_pb=_b('\n\x0bresys.proto\x12\x05resys\"1\n\x05\x45vent\x12\x0c\n\x04user\x18\x01 \x01(\x05\x12\x0c\n\x04item\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61te\x18\x03 \x01(\t\"\x12\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x32=\n\x05Resys\x12\x34\n\x11GenerateRecommend\x12\x0c.resys.Event\x1a\x0b.resys.Item\"\x00(\x01\x30\x01\x42\x1c\n\x07io.grpcB\nResysProtoP\x01\xa2\x02\x02RSb\x06proto3')
)




_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='resys.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='resys.Event.user', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item', full_name='resys.Event.item', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='date', full_name='resys.Event.date', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=71,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='resys.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='resys.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['Event'] = _EVENT
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), dict(
  DESCRIPTOR = _EVENT,
  __module__ = 'resys_pb2'
  # @@protoc_insertion_point(class_scope:resys.Event)
  ))
_sym_db.RegisterMessage(Event)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'resys_pb2'
  # @@protoc_insertion_point(class_scope:resys.Item)
  ))
_sym_db.RegisterMessage(Item)


DESCRIPTOR._options = None

_RESYS = _descriptor.ServiceDescriptor(
  name='Resys',
  full_name='resys.Resys',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=93,
  serialized_end=154,
  methods=[
  _descriptor.MethodDescriptor(
    name='GenerateRecommend',
    full_name='resys.Resys.GenerateRecommend',
    index=0,
    containing_service=None,
    input_type=_EVENT,
    output_type=_ITEM,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESYS)

DESCRIPTOR.services_by_name['Resys'] = _RESYS

# @@protoc_insertion_point(module_scope)
