# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import resys_pb2 as resys__pb2


class ResysStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GenerateRecommend = channel.stream_stream(
        '/resys.Resys/GenerateRecommend',
        request_serializer=resys__pb2.Event.SerializeToString,
        response_deserializer=resys__pb2.Item.FromString,
        )


class ResysServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GenerateRecommend(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ResysServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GenerateRecommend': grpc.stream_stream_rpc_method_handler(
          servicer.GenerateRecommend,
          request_deserializer=resys__pb2.Event.FromString,
          response_serializer=resys__pb2.Item.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'resys.Resys', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
